name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install build tooling
      run: |
        python -m pip install --upgrade pip build setuptools wheel

    - name: Install package (editable) and test deps
      run: |
        pip install -e .
        pip install pytest

    - name: Run tests
      run: |
        pytest -q

    - name: Build sdist and wheel
      run: |
        python -m build --sdist --wheel

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-artifacts
        path: dist/
